FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    net-tools \
    keepalived \
    haproxy

EXPOSE 80
EXPOSE 8444

ENTRYPOINT [ \
    "/bin/sh", \
     "-c", \
     "keepalived -D -f /etc/keepalived/keepalived.conf && haproxy -f /usr/local/etc/haproxy/haproxy.cfg" \
]
