server:
  shutdown: graceful

spring:
  config:
    import:
      - application-prod-wiki.yml
      - application-actuator-prod.yml

  lifecycle:
    timeout-per-shutdown-phase: 30s

  datasource:
    url: jdbc:mysql://${db.endpoint}/${db.dbname}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${db.username}
    password: ${db.password}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate

  mail:
    host: ${mail.host}
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 30000
          starttls:
            enable: true

distribute:
  server:
    count: ${distribute.server.count}
    index: ${distribute.server.index}

admin:
  secret: ${admin.secret}
